### ISSUE TITLE
Hound Git Configuration

### ISSUE THREAD

**Issue by pradeepmurugesan** [hound-search/hound#162]
Hi,

 I am running docker on windows host. I am facing an issue in cloning a private repo.
1. Using Https.
   
   This is my local codebase(local version of gitlab) and the cert is ofcourse not verified. So I have added 
   
   ```
   git config http.sslVerify false
   ```
   
   and tried to clone the repo manually as a docker user and root in the VM that docker created. It works fine. Tried from windows host as well it works fine.
   
   But when I tried to add that repo to config.json and issue

```
   docker run -it --rm -p 6080:6080 --name houndd -v $(pwd):/hound etsy/hound
```

 I am facing the cert error saying it could not clone since the cert is not verified.
1. Using ssh keys
   
   Now I have generated ssh pair as in https://help.github.com/articles/generating-ssh-keys/ for both docker user and root user and  tried manually say **git clone**  from terminal and it works. 
   
   But the same url given in config.json says unauthorised public key.
   
   I tried to go through the source and found Hound uses GitDriver in git.go.

I have a couple of questions here.
1. Which git does hound uses when say return &GitDriver{}, nil .
2. Is there a way to externally configure hound's git to ignore cert or to use the ssh keys.

Pradeep.

**Comment by miketheman** [comment]
Looking at the code for GitDriver's Clone operation: https://github.com/etsy/hound/blob/593f126367332cf9a8a959ec7979119c70a68479/vcs/git.go#L59-L74

I can conclude that hound is bascially shelling out to execute a git command.

You've confirmed that when setting `git config http.sslVerify false` on your host, everything works locally, so the question I would ask is "how does one set `git config http.sslVerify false` inside the container?"

The same would apply to "how are you getting the ssh keys into the container to be made avaialble for hound?"

**Comment by dschott68** [comment]
Closing this as previous comment hopefully help you out. If you still have issues, feel free to reopen.
