### ISSUE TITLE
Client browser hangs if the search query is ".*"

### ISSUE THREAD

**Issue by tpcwang** [hound-search/hound#176]
This isn't really an important issue as it isn't a query that has a valid use case, but I wouldn't have expected it to hang on all the browsers that I have tried (Chrome, FF, Edge). The bug is probably in the rendering/frontend layer as using the api works just fine (i.e. this returns results: http://codesearch/api/v1/search?stats=fosho&repos=*&rng=%3A20&q=.*&i=nope&files=)

**Comment by kellegous** [comment]
I bet you have a lot of repos, right? There is a guard against returning too many results but it is per repository.

**Comment by tpcwang** [comment]
I don't have original Hound setup any more, but I only had a handful of repos, although their size isn't that small.

**Comment by dschott68** [comment]
I tried a search query with ".*" on a hound setup with 80+ of repos and it quickly return "Error": "search exceeds limit on matches: 5000".  I am going to close this issue out.  If you wish to reopen with additional information or have a Pull Request, please feel free to reopen.  Cheers!
