### ISSUE TITLE
"Repos Summary" - Feature search for quick navigation

### ISSUE THREAD

**Issue by AvnerCohen** [hound-search/hound#182]
Thanks for Hound ! Awesome work.

We have an issue, and before digging into the code to see if we can improve, was wondering if maybe I'm just missing something.

We have many repositories (> 100) indexed using hound. Sometimes you have to search for a term that exists in multiple places and returns way too many results.

In this instances, it would really be good if I could get the results grouped by repo in a collapse/expand sort of view. This way I can:
1. At a glance, see what the overall picture of results (and maybe tune the query).
2. Be able to drill down into the specific repo without needing to scroll through pages of less relevant results.

Thoughts?

**Comment by kellegous** [comment]
Totally agree. I have been wanting to add a section to the UI that allows you to easily navigate amount the repos included in the result set.

**Comment by intiocean** [comment]
+1

**Comment by pfrandsen** [comment]
+1 for this. We just started using Hound at work (awesome tool) and are indexing around 600 repos. It would be really nice to have a list of matching repos (result overview) with links to the matches for a given repo.

**Comment by AvnerCohen** [comment]
@kellegous you looking for someone to take a stab at this? any pointers to the specific implementation you maybe had in mind, but not the time?

**Comment by tanyunshi** [comment]
:+1: collapse/expand view would be very nice for a large amount of repositories.

**Comment by salemhilal** [comment]
Hey @Roguelazer, are you talking about [this issue specifically](https://github.com/hound-search/hound/pull/235/files)? If you're willing to bring it up to date I can take a crack at it shortly. Otherwise, I can look on Wednesday.
