### ISSUE TITLE
Incorrect URL when file path contains a plus sign

### ISSUE THREAD

**Issue by mpcabd** [hound-search/hound#191]
When a file path contains a plus sign (who does that? anyway) the link doesn't have the correct URL so it doesn't work.

File path in git: `path/to/file+with+plus+signs.txt`

Invalid (current) link: `https://path.to.git.web.com/git/?p=repository.git;a=blob;f=path/to/file+with+plus+signs.txt;hb=HEAD`

Correct link should be: `https://path.to.git.web.com/git/?p=repository.git;a=blob;f=path/to/file%2Bwith%2Bplus%2Bsigns.txt;hb=HEAD`

**Comment by egonSchiele** [comment]
@mpcabd this seems to work for me. I made this file: https://github.com/egonSchiele/hound/blob/master/ui/test+file+with+plusses.markdown

I see it in the UI: http://i.imgur.com/AauvmEX.png

And the link is: https://www.github.com/egonSchiele/hound/blob/master/ui/test+file+with+plusses.markdown

I think your browser should convert those plusses to %2B's automatically.

**Comment by dschott68** [comment]
[PR 321](https://github.com/hound-search/hound/pull/321) likely resolved this issue also.  Closing this issue, but please feel free to reopen or make a Pull Request if you wish.  Cheers!
