### ISSUE TITLE
Hound doesn't consider "?q=foo+bar" equivalent to "?q=foo%20bar"

### ISSUE THREAD

**Issue by avar** [hound-search/hound#209]
I'm fairly sure [this isn't standards compliant](http://stackoverflow.com/questions/22850844/html-form-is-converting-spaces-to-instead-of-20-when-building-url). In any case having an external web form that submits data to hound and searching for e.g. "foo bar" will result in "?q=foo+bar", which hound treats as a literal "+".

Instead it should treat "+" and "%20" as equivalent, and searching for a plus should be %2B.

**Comment by dschott68** [comment]
Hello.  This issue was resolved with [PR 321](https://github.com/hound-search/hound/pull/321)
