### ISSUE TITLE
Option to generate the search index separately

### ISSUE THREAD

**Issue by mikepurvis** [hound-search/hound#214]
If I have a Jenkins instance, I might want to use that to periodically generate the search index, especially if I already have all the source sitting there, and can save doing a ton of git pulls. Allowing the index to be generated asynchronously also means less downtime— you just pop to the new index when it's ready, rather than having to grind through all the repos every time on startup.

**Comment by kellegous** [comment]
Hound already does asynchronous indexing internally. If you give hound a file:// url on the jenkins server and then do push updates (https://github.com/etsy/hound/blob/master/config-example.json#L58). Triggering a push update isn't very well documented currently. You just need to POST to `/api/v1/update` with the list of repos that need to be updated. The downside of this approach is you'll still end up with multiple copies of the repo (the original and the copy that hound uses for indexing). There have been a few attempts to add a feature to Hound where you can use an existing repository without making a copy, but Hound currently assumes that the repository files will not be edited during indexing and that's a hard thing to enforce on an external directory.

**Comment by dschott68** [comment]
Hello.  We are going to close this based on the previous comment suggestion to POST to `/api/v1/update`.  Feel free to reopen if you feel you'd like to keep it open and/or open a Pull Request.  Cheers.
