### ISSUE TITLE
Use the distance between a pair of trigrams to reduce the matching candidate set

### ISSUE THREAD

**Issue by sschuberth** [hound-search/hound#227]
The idea for this performance improvement is stolen from [zoekt](https://github.com/google/zoekt). For some background discussion please see @spearce's [post](https://groups.google.com/d/msg/repo-discuss/oJO2EkkLo4M/x3cEU_FQBAAJ) on the Gerrit mailing list.

**Comment by dgryski** [comment]
Switching to positional index would be a very fundamental change to how all the code search logic works

**Comment by sschuberth** [comment]
I see. So if you feel it's not worth it, feel free to close this issue.

**Comment by hanwen** [comment]
Rather than rewriting the code, you could integrate the actual zoekt code. I'd be happy to help.

**Comment by dgryski** [comment]
@hanwen Maybe the easier thing is to go the other way: integrate search index auto-updating and a prettier front-end into zoekt.

**Comment by bschlenk** [comment]
How much of a performance improvement? Can we see some numbers comparing identical setups? Hound is already blazing fast. I've never had a search take over a second on searches with 150+ repos. My typical search takes ~200ms.

**Comment by hanwen** [comment]
@bschlenk - how many files and how much bytes do these 150 repos cover?

Is there an interesting corpus we could agree on? Maybe something medium sized like the linux kernel or webkit? Or something large like https://chromium.googlesource.com/chromium/src/ ?

**Comment by hanwen** [comment]
for rare strings for files in cache, results take ~10ms typically.

Try http://cs.bazel.build/search?q=r%3Atorvalds+crazy+idiot&num=50

(you can try other queries with "r:torvalds" to restrict to the linux kernel.)

**Comment by hanwen** [comment]
I did a bit of benchmarking on the linux kernel on my laptop. 

Searching for a rare string like "crazy" or "vmsplice" in the linux kernel takes about 30-50ms on Hound.

On Zoekt, this takes about 1-2ms.

**Comment by dgryski** [comment]
I got a 10x speedup switching from linear scan to galloping search for my own postings list code: https://github.com/dgryski/go-postings/commit/c5076451beb432f81f5f3a789ff3bf7991b55a76

**Comment by dschott68** [comment]
Hi. Is this still an enhancement you are pursuing?

**Comment by sschuberth** [comment]
Who is "you" in that sentence? Because so far no one has been pursuing this enhancement AFAIU, in the sense to actually look into implementing it.

**Comment by salemhilal** [comment]
I'm gonna close this issue. If there's interest in adopting zoekt, we can reopen it, but given that hound's speed isn't a huge concern, I think effort could be better spent on other issues.
