### ISSUE TITLE
Windows: Path too long error on file:// local repo

### ISSUE THREAD

**Issue by MartinKuhne** [hound-search/hound#266]
fatal: cannot create directory at '(long path name)': Filename too long

Windows has a MAX_PATH limit of around 256 characters. Programs can use an alternative syntax to gain access to longer path names. This is documented at https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx#maxpath

**Comment by salemhilal** [comment]
I'm going to close this for now, but I'd love more details on reproducing this issue locally (does it happen when building, serving, etc.)
