### ISSUE TITLE
Merge the two Makefiles into one

### ISSUE THREAD

**Issue by sahildua2305** [hound-search/hound#270]
Action points (copying from this [comment](https://github.com/etsy/hound/pull/256#issuecomment-352908917)):

1. Update the README.md with steps to clone hound into a GOPATH.
1. Merge the two Makefiles and just have the single Makefile assume that the source is on the GOPATH. (Maybe there is a way to double check that the code really is in the right directory).

For context: read comments [here](https://github.com/etsy/hound/pull/256).

**Comment by jazzdan** [comment]
This can be assigned to me, I'll take a look this weekend.

**Comment by salemhilal** [comment]
Hey @jazzdan (hi!) — what's the status on that fork?

**Comment by jazzdan** [comment]
Hey @salemhilal it looks like the whole tools directory and its Makefile was deleted and now there's only one Makefile so I think this issue can be closed and my fork deleted. :)

**Comment by salemhilal** [comment]
@jazzdan thank you! I just wanted to make sure I wasn't missing anything. I'm gonna close this issue.
