### ISSUE TITLE
Time to release a new version?

### ISSUE THREAD

**Issue by sahildua2305** [hound-search/hound#276]
The last release was three years ago. Is there a reason for not releasing it for a long time?

/cc @kellegous

**Comment by mwgamble** [comment]
I'd definitely appreciate a new release. It feels long-overdue.

**Comment by sahildua2305** [comment]
@kellegous what do you think?

**Comment by r3m0t** [comment]
@kellegous  @jklein would you be able to tag a release?

**Comment by jklein** [comment]
@mwgamble @sahildua2305 @r3m0t neither Kelly nor I work at Etsy anymore, so we can't do this. I'm honestly not sure who to reach out to at this point, sorry!

**Comment by r3m0t** [comment]
@SaraBee @cconstable @mchalek @macdoum1 can you tag a release?

**Comment by dschott68** [comment]
Hi @sahildua2305 Yes, we will work on a 0.3.0 release.

**Comment by dschott68** [comment]
We've posted a [v0.3.0](https://github.com/hound-search/hound/releases/tag/v0.3.0) release now.  Cheers!
