### ISSUE TITLE
error with main.go:124 +0x6ab

### ISSUE THREAD

**Issue by w0rhost** [hound-search/hound#280]
https://github.com/etsy/hound/blob/92e228e2be3d624b89e3eaf5d2a4098495937587/cmds/houndd/main.go#L124

/src/github.com/etsy/hound/cmds/houndd/main.go:124 +0x6ab

**Comment by dgryski** [comment]
If no configuration file is available, perhaps the error message could be nicer. But hound cannot proceed in that state.

**Comment by w0rzxy** [comment]
thank you very mach..

**Comment by dgryski** [comment]
So, this can either be closed or retitled "Improve error message when configuration file not found"

**Comment by w0rzxy** [comment]
因为我的config配置文件少了个大括号},所以就出错了。

**Comment by dgryski** [comment]
Recent Go versions include more information in the unmarshal error message.  Given that JSON is tricky to generate by hand (extra comma, for example), maybe the error message should be made clearer.

**Comment by w0rzxy** [comment]
thank you very mach..

**Comment by dschott68** [comment]
It seems like from the comments that this issue may not need to stay open.  If that is not correct, please feel free to reopen or make a Pull Request.  Cheers!
