### ISSUE TITLE
Is it possible to get houndd version ?

### ISSUE THREAD

**Issue by perumalpandian** [hound-search/hound#306]
As **bin/go-bindata** provides version (bin/go-bindata -version), Is it possible to get bin/houndd version ?

/hound/bin# ./go-bindata -version
go-bindata 3.1.0 (Go runtime go1.5.3).
Copyright (c) 2010-2013, Jim Teeuwen.

**Comment by kartikay101** [comment]
Anyone working on this ? If not, I'd like to pick it up.

And if you could let me know the relevant parts as well, it would be a great help

**Comment by salemhilal** [comment]
Hey @kartikay101, you’re the first person interested in this issue! The files you probably want to check are the ones in the `cmds` directory, like this one:

https://github.com/hound-search/hound/blob/master/cmds/hound/main.go#L83

It might also be a good idea to exit the command after the version string is printed. I’ll put your head on this issue.
