### ISSUE TITLE
TLS support for Hound

### ISSUE THREAD

**Issue by perumalpandian** [hound-search/hound#310]
I am trying to add TLS support for Hound and I am successful with Apache. But the problem is, I am still able to access my Hound with **http://MachineIP:8888** from external network. I want to restrict this to only localhost access. So that I can access my hound only through my apache reverse proxy. I don't want to use "**iptables**". Do we have any configurations in Hound itself ?

**Comment by mikeyrcamp** [comment]
I had something similar and ended up putting hound in a container, and only allowing external access through the apache httpd proxy.

**Comment by salemhilal** [comment]
I'm going to close this issue for now. If there are outstanding questions, feel free to reopen the issue.
