### ISSUE TITLE
Local repos could be symlinked instead of clones

### ISSUE THREAD

**Issue by nfultz** [hound-search/hound#311]
In experimenting with hound, it seems like replacing local clones with symlinks works:

```
$cd hounddata
$ls
idx-2c81735e97e5d728  idx-3945318645f67bc6  vcs-5c02f6085efcd7c4f2c4583639339d533e78a160  vcs-765a6f802ac2c02293daeeb8ee65c9ca6b80e927
$rm -rf vcs-5c02f6085efcd7c4f2c4583639339d533e78a160/
$ln -s /media/nfultz/Elements/bitbucket.org/29decibel/ vcs-5c02f6085efcd7c4f2c4583639339d533e78a160
```

Since I have a lot of repos, this could potentially reduce my disk usage a lot. Is this a bad idea?

**Comment by dubiouscript** [comment]
>Is this a bad idea?
i dk tbh , but i hear less is more 

this
> replacing local clones with symlinks works

made me thunk of 
https://github.com/taterbase/git-mount
that!


  \* why copy or link when you could :bulb: mount *

=]

**Comment by salemhilal** [comment]
I'm going to close this issue for now. If there are outstanding questions, feel free to reopen the issue.
