### ISSUE TITLE
FORK

### ISSUE THREAD

**Issue by yelizariev** [hound-search/hound#326]
I've made a fork of the project: https://github.com/it-projects-llc/hound

What have been done so far:
* [Change links in the docs](https://github.com/it-projects-llc/hound/commit/d3fb3a3d8d2f3c9156d0e5410a9de77ee8e04f31)
* Add [automatic rebuilding](https://github.com/it-projects-llc/hound/blob/master/.github/workflows/main.yml) of ``ui/bindata.go``
* [Merge](https://github.com/it-projects-llc/hound/commit/6da8145ae522e320e160038d9c22473d2380c5f6) #275 about using custom branches in git repos
* [Merge](https://github.com/it-projects-llc/hound/commit/0a5c3d5c36ac3e29b98cf562026ba3bda269b665) #324 about updating React version

[More updates coming soon](https://github.com/it-projects-llc/hound/pulls?utf8=%E2%9C%93&q=is%3Apr+).

P.S. I cannot guarantee that @it-projects-llc will actively maintain it until the time of our [team](https://www.it-projects.info/team/) is [sponsored](https://www.patreon.com/join/itpp/checkout?rid=0)

**Comment by yelizariev** [comment]
* [Merge](https://github.com/it-projects-llc/hound/pull/4) #223 about new option "exclude files"

**Comment by yelizariev** [comment]
* [merge](https://github.com/it-projects-llc/hound/pull/12) https://github.com/hound-search/hound/pull/235 about collapse\expand results

**Comment by yelizariev** [comment]
Sync with refactoring made by  @elchininet https://github.com/elchininet/hound/commit/3d31457bd3844c6d6176ce20537d9ac05b85a7ca

**Comment by yelizariev** [comment]
Simple CI tool to preview updates in PR: 

* example: https://github.com/it-projects-llc/hound/pull/16#issuecomment-559749161
* source: https://github.com/it-projects-llc/hound/blob/master/concourse.yml

**Comment by yelizariev** [comment]
Other updates are published here: https://github.com/it-projects-llc/hound/releases

**Comment by Aberrantfox** [comment]
Just as I was about to give up on this tool, thank you!

**Comment by salemhilal** [comment]
Hey @yelizariev, I want to assure you that Hound is not abandoned, and we're interested in bringing our repo to parity with your fork. We're triaging the backlog of issues and pull requests, but if there are issues that would block you from using Hound, we'll do our best to prioritize them.

There's a little more detail here: https://github.com/hound-search/hound/issues/328#issuecomment-648987144

**Comment by yelizariev** [comment]
Hi @salemhilal, my main concern is about [refactoring of *.jsx files](https://github.com/elchininet/hound/commit/3d31457bd3844c6d6176ce20537d9ac05b85a7ca) that I applied to my fork before making further updating. If it would be applied to the hound, I'd join to the hound community and send PR with the some of the features I did. 

Thanks for your efforts.

**Comment by yelizariev** [comment]
I close this issue in favor of https://github.com/hound-search/hound/issues/334 then
