### ISSUE TITLE
abandoned?

### ISSUE THREAD

**Issue by corbosman** [hound-search/hound#328]
Am I right in assuming hound has been abandoned? I have a PR waiting to add github webhooks to trigger updates, but if it's been abandoned I'll just run it off my own fork.

**Comment by jklein** [comment]
Hey @corbosman - I certainly don't have the bandwidth to maintain it at this point, and it seems like @kellegous is in a similar boat. We created this project when we were both at Etsy, and we've both been gone for a few years. It looks like the company has spun it off to its own project/namespace, so I doubt there's commitment to maintain from Etsy. If someone wants to take over this repo and keep it as the canonical source vs forking I'd be happy to add you as a contributor!

**Comment by corbosman** [comment]
Well if someone is interested, I added support for github webhooks. We run about 1500 repos from a Github Enterprise through hound, and polling was certainly not an option. There is an api call for updates, but that doesn't match a github webhook. So i added an api call that can parse a github webhook and start an index for the repo involved. You can see my patch here if someone wants to copy it to their fork:

https://github.com/corbosman/hound/commit/5c0e50f660b9a6effee3d4988333f498059c0d8d

**Comment by bgreenlee** [comment]
@corbosman Where's the PR for that? I'm not finding it.

**Comment by corbosman** [comment]
@bgreenlee  I did not actually submit the PR, figured that was kind of useless if it's been abandoned. You can see the patch on the link above.  Im just building a docker image from my own fork now.

**Comment by yelizariev** [comment]
I currently working on a project, which is based on hound. Specifically, I want to make some preview tool to get a running hound in PR. I can do it here instead of the [fork](326) and use my own servers for the tool. But all that makes sense if I get contributor access

**Comment by elchininet** [comment]
@corbosman, cc: @jklein,

I wrote @kellegous some months ago, asking this same question because Hound is actively used at my Company and I prefer to contribute to the community project than to our personal internal fork.

I have a lot of improvements to the front-end code but I didn't pushed more pull requests because the first one is waiting since September, so, if it is possible, I would like to become a contributor.

Regards

**Comment by dgryski** [comment]
I believe part of the reason it was moved to an external org was precisely so additional maintainers could be added.

**Comment by jklein** [comment]
@corbosman and @elchininet - I'm going to add you both as maintainers and close this issue. Sorry for the extreme delay here, this just hasn't been high on my priority list with my day job.

**Comment by jklein** [comment]
Oh hey, turns out I can't do that. Looks like @kellegous is the owner and I'm just a lowly member. Hopefully he can do this

**Comment by elchininet** [comment]
> Oh hey, turns out I can't do that.
Ok, let's wait for @kellegous then. Thanks.

**Comment by corbosman** [comment]
I prefer not to be a maintainer, Im not really involved in running hound in our company. I just created this patch so our github enterprise wasn't being flooded by hound.

**Comment by salemhilal** [comment]
Hey everyone,

I wanted to take a second to introduce myself, @dschott68 , @jacobrose, and @nickmoorman. We've all volunteered to help maintain the Hound project. We are all engineers at Etsy, and most of us Hound literally every day to do our jobs. Our first goal is to triage the backlog of issues and PRs, with the hope of getting a sense of what a future roadmap will look like in the process. We're still getting our feet wet here — you can help us by bumping outstanding issues and updating any outstanding PRs with tests. In the mean time, be patient with us, and know that this project is far from abandoned.

Thanks again,
Salem, David, Jacob, and Nick.

**Comment by corbosman** [comment]
@salemhilal Would you still be interested in my PR for github webhook support? It allows github to tell hound when to re-index a repo. I dont have any tests in it, my go knowledge is too basic. But we run this in production. You can see my patch here: https://github.com/corbosman/hound/commit/5c0e50f660b9a6effee3d4988333f498059c0d8d

But I can just make a PR if you're interested in it.

**Comment by salemhilal** [comment]
@corbosman I think that'd be a great PR to have. Your commit looks pretty straightforward, too (and the fact that it's running in prod for you is reassuring). That API file definitely needs some tests, and this could be a good first test to write. I think you'll need to:
1. take that request handler and put it into its own function
2. test it using the `httptest` package.

I put a simple request handler test together in the go playground [here](https://play.golang.org/p/UNaUdUYjy_V) which might be helpful. My go is a little rusty though, so I'm happy to help or clarify with these tests. The tests don't have to be too intense; I think just having a test file for the API package would be the most useful thing.
