### ISSUE TITLE
Docker image not updated since Nov. 2018

### ISSUE THREAD

**Issue by legoktm** [hound-search/hound#332]
The [etsy/hound docker image](https://hub.docker.com/r/etsy/hound/tags) advertised in the README hasn't been updated since "[11/2/2018 at 3:26 am](https://hub.docker.com/r/etsy/hound/tags)".

Can the github -> docker hub integration be restored? Or maybe the image needs to be under a different name now? Idk.

**Comment by salemhilal** [comment]
The original image is owned by Etsy, but this project is no longer maintained by Etsy. We can look into setting up a docker account and publishing a new image.

**Comment by legoktm** [comment]
> We can look into setting up a docker account and publishing a new image.

That would be wonderful. Please let me know if you need any help doing so, I've set it up for other repos before. Here's the documentation: https://docs.docker.com/docker-hub/builds/

**Comment by inful** [comment]
See #401 for implementation of automatic docker image building to ghcr.io

**Comment by oscrx** [comment]
With the changes i proposed in #463 this should be trivial.

But the Docker hub account should be maintained by someone here.
hound-search as account name is not allowed. 
The same for hound_search.
hound is already taken.
And houndsearch I just reserved myself. Let me know who will/should manage this account.

**Comment by kellegous** [comment]
The `etsy` organization in hub.docker.com was transferred to Etsy July 8, 2022. I coordinated the transfer with August Hall. Perhaps some of the folks here still employed at Etsy could request that the hound repo be removed from that organization.

**Comment by oscrx** [comment]
How does #401 resolve this issue?

**Comment by dschott68** [comment]
mistakenly closed since we publish to http://ghcr.io/hound-search/hound:latest and https://github.com/hound-search/hound/blob/main/README.md#run-with-image-from-github shows that.  However, we still need to see if old https://hub.docker.com/r/etsy/hound can be deleted as that is not longer maintained.

**Comment by dschott68** [comment]
note that https://hub.docker.com/r/etsy/hound/ has now been removed.  https://github.com/hound-search/hound/pkgs/container/hound and http://ghcr.io/hound-search/hound:latest that points to it should be the place to go now.

**Comment by oscrx** [comment]
I reserved houndsearch on Docker hub if you'd like to publish the images there as well
https://hub.docker.com/u/houndsearch
