### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by jacobrose** [hound-search/hound#350]
Our installation instructions don't necessarily work for first-time Go users. Working from a machine (or vm!) that's never had Hound, Go, npm, etc. installed, we should go through the steps and ensure that a successful build can be achieved, or make any corrections needed to help first-time users get Hound up and running on their systems.

**Comment by rfan-debug** [comment]
Hi, @jacobrose i am looking at this issue now. I am writing some documents to describe how to setup from a clean VM.

May i know what kind of operating system you are using?

**Comment by salemhilal** [comment]
@rfan-debug and I talked offline, but for some context:
* This issue is something that having a few people onboard with would be helpful.
* Jacob is a maintainer as well — we added this issue ourselves.

**Comment by salemhilal** [comment]
I'm going to assign this to myself, since I've been having everyone walk through this issue as their onboarding.

**Comment by rfan-debug** [comment]
Hey, @salemhilal sorry for the delaying. I have some stuff here: https://github.com/hound-search/hound/pull/359

I am still testing the docker solutions.

**Comment by rfan-debug** [comment]
@salemhilal should we close this issue? #359  has been merged.

**Comment by salemhilal** [comment]
@rfan-debug I wanna leave this open for now. I want a few more people working on different platforms to vet the installation instructions before I close them out.

**Comment by jrarmstro** [comment]
The installation instructions worked well on Ubuntu Focal.

**Comment by salemhilal** [comment]
We've just updated the README to use the newer ghcr.io image repo, which should clarify installing Hound via Docker. I'm going to close this, but we can always re-open if the installation instructions are still confusing.
