### ISSUE TITLE
Missing margin between advanced pane input boxes

### ISSUE THREAD

**Issue by salemhilal** [hound-search/hound#358]
We need some margin between the "File path" and "Exclude file path" inputs. Bonus points if you can do this in a way that makes adding future inputs easy as well. 

<img width="759" alt="image" src="https://user-images.githubusercontent.com/819218/96283780-b1656000-0faa-11eb-8dc9-18f6f7b8edee.png">

**Comment by blobbered** [comment]
i'd like to take this one on. =)

**Comment by salemhilal** [comment]
This was fixed in #361 (thank you!)
