### ISSUE TITLE
Switch default branch to `main`

### ISSUE THREAD

**Issue by salemhilal** [hound-search/hound#364]
As of #345 Hound has support for default branches other than `master`. It makes plenty of sense that Hound itself set its [default branch to `main`](https://github.com/github/renaming).

**Comment by arne-rusek** [comment]
A lot of repositories still use `master` as default branch and I would imagine some of them will still keep it. Could hound maybe support both? I.e. for new repos and those whose owners renamed default branch to `main` but also older repos which for any reason have not renamed the `master` to `main`?

**Comment by salemhilal** [comment]
Hey @arne-rusek, this issue is specifically about the hound repository itself. This repo's default branch should be `main`. Hound itself currently supports any name of default branch, and should be able to auto-detect the default branch name of most git repos.

**Comment by zonk1** [comment]
> Hey @arne-rusek, this issue is specifically about the hound repository itself. This repo's default branch should be `main`. Hound itself currently supports any name of default branch, and should be able to auto-detect the default branch name of most git repos.

Oh, I did not read the description properly, thank you for explanation.

**Comment by salemhilal** [comment]
No worries, it's worded a bit confusingly.
