### ISSUE TITLE
Add documentation for all the config options

### ISSUE THREAD

**Issue by salemhilal** [hound-search/hound#367]
`config-example.json` is pretty through, but being that it is a json file, it's hard to be verbose or descriptive. Add a `/docs/config-options.md` (or something similar) and document each of the config options.

Things that need documentation:

- [ ] `max-concurrent-indexers`
- [ ] `dbpath`
- [ ] `title`
- [ ] `health-check-uri`
- [ ] `vs-config`
- [ ] `repos`
- [ ] git config options
- [ ] hg config options
- [ ] svn config options

**Comment by ehrktia** [comment]
@salemhilal , @dschott68  @jacobrose  @nickmoorman  i would like to volunteer for this topic.
Already have a branch locally with below content in `docs/config-options.md`
ConfigOption | Description
:------ | :-----
MaxConcurrentIndexers | defines the total number of indexers required to be used for indexing code. If not provided defaults `2`
HealthCheckURI |  health check url for hound , if not provided defaults to `/healthz`
DbPath | absolute file path where the `config.json` file exists. By default is `data`
title | Title used for the application.Defaulted to 'Hound'
url-pattern | composed of base url and anchor values in form of key value pairs.
vs-config | holds the version control config, default VCS used in Hound is git.Other options for VCS are svn,mercurial,bitbucket,hg, etc.Refer to `config-example.json` to get the list of vcs and usage
Repos | holds the list of repos which are required to be indexed by Hound . Each Repo is added with reponame as a Json Key with options associated with repo as values similar to example provided in `config-example.json`


gitOptions  | Description
:------ | :-----
ms-between-polls | time interval to poll the repo url ,default is `30s`
detect-ref    | used to determine branch , defaults to `master` branch 
ref | used to provide reference for the branch for repo.

svn-options  | Descriptions
------ | -----
username  | user name for the svn repo
password | password to authenticate use for svn repo.

url-options | Description
------ | -----
url-pattern | when provided used by Hound for config, else defaults to `{url}/blob/{rev}/{path}{anchor}`
anchor | when provided used for vcs config else set to `#L{line}`

**Comment by jacobrose** [comment]
@ehrktia Sounds great -- would you please submit a pull request? Thank you very much for volunteering!

**Comment by ehrktia** [comment]
@jacobrose sorry for trouble again, i tried to push my branch and getting 403
```
 ~/hound  documentation-config-json ±  git push -u origin documentation-config-json
remote: Permission to hound-search/hound.git denied to ehrktia.
fatal: unable to access 'https://github.com/hound-search/hound.git/': The requested URL returned error: 403
```
Tried to open a pull request as i do not have a branch available with my changes had to wait.
is there any permission i require to push in to the repo.

**Comment by p3732** [comment]
I think it would also be helpful to add the unit for `ms-between-polls` (I assume it is milliseconds because of the name, which seems excessive, but I don't know).

**Comment by StingyJack** [comment]
Also any advice regarding theoretical or practical limitations (does it make sense to have 200 indexers, for example) would be nice

**Comment by salemhilal** [comment]
Hey, I'm gonna close this issue out, but if there are outstanding issues, I can re-open it. 
@StingyJack, to answer your question, I think the indexer count would depend on the system, so a bit of test-and-time might be the best approach. I'd recommend using an indexer per available core on your machine to start.
