### ISSUE TITLE
Docker Image: Handle the bzr package being removed from Alpine Linux

### ISSUE THREAD

**Issue by yayachiken** [hound-search/hound#375]
As I found out on the discussion PR #371, Alpine Linux dropped the `bzr` package in the releases 3.12 and onwards. For that reason, the Dockerfile currently pins the latest Alpine Linux 3.11.x release.

Alpine Linux 3.11.x is still supported, but when that gets EOL this would become a problem, as the Docker image could not be built anymore with a current image receiving security fixes etc.

I see the following two solutions to the problem:

1. Remove `bzr` support from the Docker image by simply omitting that package from the Dockerfile. This would obviously be a loss of functionality and is probably not the way to go unless no other alternatives are possible.
2. Base the Dockerfile on another base image which still contains `bzr`. In that case the Dockerfile would have to be rewritten to replace distribution specific commands like `apk` with the equivalents of the newly chosen base image distribution.

**Comment by salemhilal** [comment]
(This could just as well be marked as a bug, since this would be breaking after Alpine Linux 3.11.x is EOL'd)

**Comment by foragerr** [comment]
Do you folks have a preferred base image as an alternative to alpine?

I have an unrelated DNS resolution issue with running the alpine based image in AWS Fargate. I'm about to create my own hound image from scratch, happy to go with a base image you may have an affinity for, and contribute it back.

**Comment by foragerr** [comment]
aside: The comment on this alpine commit says to use breezy as a replacement for bzr

>Python2 only with no upstream. Most distros replaced it with breezy
which uses python3 and if there is demand for bzr then breezy and its
dependencies should be packaged instead

https://gitlab.alpinelinux.org/alpine/aports/-/tree/3.12-stable/unmaintained%2Fbzr

**Comment by dschott68** [comment]
resolved with https://github.com/hound-search/hound/pull/429
