### ISSUE TITLE
Use //go:embed from Go 1.16

### ISSUE THREAD

**Issue by simon04** [hound-search/hound#381]
https://golang.org/pkg/embed/

>  Package embed provides access to files embedded in the running Go program.
>
> Go source files that import "embed" can use the //go:embed directive to initialize a variable of type string, []byte, or FS with the contents of files read from the package directory or subdirectories at compile time. 

https://golang.org/doc/go1.16#library-embed

**Comment by salemhilal** [comment]
Hey! Just to clarify, are you proposing that this replaces `ui/bindata.go` and the `go-bindata`package?

**Comment by simon04** [comment]
Exactly, yes.

**Comment by salemhilal** [comment]
Ok, cool. We aren't going to prioritize this for the time being, but we are open to a PR.

**Comment by moson-mo** [comment]
Seems like the main blocker is that with the switch to `embed`, a simple `go install ...` won't work anymore / people would need to have `npm` installed as well when compiling hound?

I'd agree with 3 points mentioned here: https://github.com/hound-search/hound/pull/430#issuecomment-1172640962

Regarding _Commit the ui build artifacts to the repo_:  
That's actually what's already happening with `bindata.go`. Switching to `embed` would just shift that to different files.
(which I find somewhat dangerous.  It's much easier to hide malicious stuff in "binified" go files or minified JS) 😉

**Comment by dschott68** [comment]
resolved by https://github.com/hound-search/hound/pull/460 and thank you!
