### ISSUE TITLE
Compile and bundle JavaScript using esbuild

### ISSUE THREAD

**Issue by simon04** [hound-search/hound#382]
https://esbuild.github.io/ – esbuild is

> An extremely fast JavaScript bundler

It provides a CLI and a Go API, see https://esbuild.github.io/api/

It might be used to streamline the bundling and replace the webpack config.

**Comment by salemhilal** [comment]
I'm actually pretty excited about ESBuild outside of Hound. Hound isn't a huge JS project, so while switching out JS build systems would be relatively easy, I don't know if it's a priority. I'd be interested in trying it out later, once ESBuild has wider community support. I'm going to close this, but if there are strong reasons to re-open it and prioritize it, I am not opposed to that.
