### ISSUE TITLE
Advanced controls (#adv) blocked by default uBlock Origin Russian list

### ISSUE THREAD

**Issue by legoktm** [hound-search/hound#385]
I'm forwarding a report from https://phabricator.wikimedia.org/T275820 that the advanced form, which uses the id `adv`, is in the default blocklist for Russian users of uBlock Origin (and probably other ad blockers), see https://easylist-downloads.adblockplus.org/advblock+cssfixes.txt

Would you be open to renaming the field to something like "advanced" which I think would be clearer and also not likely to be included in default block lists? I think it should be trivial to do and provide a better experience for some users. I'm happy to provide a PR as well, if it would be accepted.

**Comment by salemhilal** [comment]
Sorry for the late reply here! This sounds super reasonable and we would be totally down to accept a PR for this.

**Comment by jeffswensen** [comment]
Addressed in #449
