### ISSUE TITLE
feature request: load repos on demand and cache them for a while

### ISSUE THREAD

**Issue by SuperSandro2000** [hound-search/hound#389]
I think it would be a nice new feature if you could load github repos on demand and index them (even if it takes a few seconds to a minute) and if you did not use them for a day they are dropped again from the cache automatically.

I am browsing and searching a lot of repos on GitHub and the search does not fit my needs to find basic strings in the entire repo. I want to avoid online alternatives.

**Comment by nickmoorman** [comment]
Hi!  Thanks for the feature request.  This is a neat idea, but what you've proposed doesn't quite fit in with Hound's core functionality, and it would require a fair amount of effort to move things around to properly support this feature.  I know it's a bit of a hassle, but as a workaround, you could edit your Hound config and restart the server to add these "temporary" repositories.  Hopefully this is an acceptable alternative.  Feel free to re-open this issue if you'd like to discuss further.  Thanks again!
