### ISSUE TITLE
Question: Can multiple server instances share a filesystem?

### ISSUE THREAD

**Issue by ianfixes** [hound-search/hound#390]
I'm running hound in AWS Fargate, which seems to crash fairly frequently.  The crashes would be less concerning if there was persistent storage so that a reboot does not entail a re-index.  But if I set up hound with a persistent (& shared) filesystem, will that cause collisions among the individual server instances?  Or is there already locking in place that will handle that? 

I'm hopeful that the concurrent indexers option mentioned in the code is capable of accommodating indexers that might be running on separate machines entirely.  Is that a bad assumption? Or do I need to just experiment for myself?

**Comment by salemhilal** [comment]
Hey! I don't think we have specific knowledge of how Fargate operates, so I'm not sure I can answer your question as well as I'd like to. Maybe to start, can you tell me more about these crashes? If you plan to run multiple instances of Hound and have them share one `data/` directory, I believe that is undefined behavior. I think Hound was implemented with the assumption that each service is responsible for managing its own data folder.

**Comment by ianfixes** [comment]
Fargate is just "containers-as-a-service" that AWS offers -- For that, I'm using an image based on https://github.com/hound-search/hound/blob/main/Dockerfile

I run hound as a few parallel tasks behind a load balancer, so each of them maintains its own index in its own ephemeral filesystem.  It sounds like giving each host a persistent filesystem will be fine, but not a _shared_ persistent filesystem.

I'm not sure if "crashes" is too strong of a word for the behavior I'm seeing, but the symptom is that the container fails its health check (which I've defined as `curl localhost:6080/healthcheck | grep "$(printf '\xF0\x9F\x91\x8D')"` -- checking that the healthcheck is the 👍 emoji).  I'm not clear on the circumstances under which this would happen, but the lack of text output to the logs at the time of the failed check makes me think it happened suddenly.  I could be way off.

**Comment by salemhilal** [comment]
I'd agree that giving each host its own persistent filesystem is the right way to go here. I'd love to know if you have any more clues about these healthchecks, or if you can repro anything about these crashes. I'm going to close this issue out just to help us prune our backlog a little bit, but feel free to reopen it with additional details. I'm sure you aren't the only person who will want to get Hound working with Fargate.

**Comment by ianfixes** [comment]
I was able to find the root cause of the "crash": the Fargate health check command was really having trouble with the unicode character.  Thinking that the task was unhealthy, the service was periodically killing it and starting new instances.

For our health check monitor to ensure that hound's `/healthcheck` endpoint returns `👍`, we need to encode that character not only in the shell command that Fargate will run but _also_ encode the command in the YAML file that configures the task.  And we had unwittingly made an error in our escaping of those strings.  Ultimately we just converted to hex and grepped on that instead:

```bash
# you have to "just know" that this is the thumbs up.
wget -q -O - http://localhost:6080/healthcheck | xxd | grep "f09f 918d 0a"
```

Although the unicode `👍` is certainly "modern"/clever/cute, it also ended up being a time sink to debug -- AWS does not provide logs for the output of the health-checking command.  I'd love the ability to pass in our own string (via an environment variable) that the health check would return to us as its "healthy" response; that way we might choose something that encodes more easily.

**Comment by salemhilal** [comment]
Hey, thank you for sharing that investigation, and I'm sorry it caused you so much grief! I think having a configurable healthcheck string is totally reasonable. If you are open to contributing that, we would accept a PR. Otherwise, I'll add an issue for it since it's worth tracking.

**Comment by ianfixes** [comment]
I don't have enough familiarity with golang (& its practices) to contribute a patch -- it would likely take your team longer to coach me through the PR than to just write it.

Please link the issue here, I'd be glad to drop some context into it.
