### ISSUE TITLE
Is there any way to save or export the results?

### ISSUE THREAD

**Issue by StingyJack** [hound-search/hound#400]
I can open the Dev Tools in the browser and pick the `search?` row from the network panel and get them that way. I was looking for a link button or something on the page. Is there one I'm just not seeing or is this not an available function?

**Comment by salemhilal** [comment]
Hey! This is not a function built into the UI, but you can hit the `/search` endpoint and do anything you'd want with that data directly. Are you looking for something like an `export as json` button or something?

**Comment by StingyJack** [comment]
Thanks, I ended up making a powershell function to do this, but yeah an export button that would dump out the search criteria, date, and results
