### ISSUE TITLE
Run / automate Golang linting

### ISSUE THREAD

**Issue by salemhilal** [hound-search/hound#412]
We should be linting our go code! 
A first pass at this was done as part of [this PR](https://github.com/hound-search/hound/pull/341). 
We'll want to find a go linter — `go lint` has long since been deprecated. [Staticcheck](https://staticcheck.io/) and [go vet](https://pkg.go.dev/cmd/vet) are potential alternatives.

**Comment by dschott68** [comment]
Is this different that the existing Github Action https://github.com/hound-search/hound/runs/4954299890?check_suite_focus=true   ???

**Comment by salemhilal** [comment]
Ah yes it is! I assumed that since we closed the PR to delete unused code that linting had never been set up, but that's not true at all. I'm gonna close this.
