### ISSUE TITLE
installation instructions don't work

### ISSUE THREAD

**Issue by undergraver** [hound-search/hound#423]
Hi,

I am not familiar with go and its particularities. I find the configuration tutorial lacking some bridge for the less accustomed to go language.

My version of go:  

```
# go version
go version go1.18.2 linux/amd64
#
```

When I try this I get an error:
```
# go get github.com/hound-search/hound/cmds/...
go: go.mod file not found in current directory or any parent directory.
        'go get' is no longer supported outside a module.
        To build and install a command, use 'go install' with a version,
        like 'go install example.com/cmd@latest'
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.
#
```

Can somebody help me installing this? I promise I will do a pull-request.

**Comment by wilricknl** [comment]
Hi there, 

I ran into the same issues today. The thing that worked for me is the following:

```shell
git clone https://github.com/hound-search/hound.git
cd hound
go build ./cmds/hound
go build ./cmds/houndd
sudo mv hound houndd /usr/local/go/bin/
```

You might have to change the path of the last command if you installed Go somewhere else on your system. I hope this helps!
