### ISSUE TITLE
Search results are incomplete

### ISSUE THREAD

**Issue by heyingjiee** [hound-search/hound#424]
I'm pretty sure there are some fields that exist in the warehouse but are not searchable

When I select the two repositories, I can search the result for the yiche-charge-mini-program
![image](https://user-images.githubusercontent.com/39174971/174296173-959672c9-7463-4a61-a657-18aafb377e55.png)

If I choose to retrieve only one repository, yiche-charge-mini-program, I get unsearchable results
![image](https://user-images.githubusercontent.com/39174971/174297750-a6c8293f-b52a-45e1-ba34-3787a337509d.png)

**Comment by heyingjiee** [comment]
sorry,is my fault，I entered an extra space when configuring the warehouse name

**Comment by salemhilal** [comment]
No worries at all! Thank you for submitting regardless, and let us know if you run into any other problems.
