### ISSUE TITLE
Ignore Case by Default

### ISSUE THREAD

**Issue by andrewjtimmons** [hound-search/hound#434]
Hello!

Is it possible when compiling hound to run in go to pass an arg to ignore case by default? I see the flag for the ui is set here https://github.com/hound-search/hound/blob/b1bc7538503286dbf3e9dd7b98c557060c327884/cmds/hound/main.go#L88.

Another thought is that I could write a PR to this repo that would ignore case by default, but I can understand if some people prefer the default the other way.  I read the contribution guidelines and would be happy to put a pr, but want to make sure such a change has a reasonable chance of being merged before committing to it.

My usecase is that different languages might have different case patterns, so unless I remember to uncheck the box tracking down how args pass between service boundaries and language boundaries is tricky.

Have a nice day,
Andy

**Comment by salemhilal** [comment]
Hey! I think it'd be tricky to change that particular default while still having the search string treated like a regular expression. We've talked about a simplified vs advanced querying syntax option that would allow you to search via string matching (like you would in a browser, ignoring case, etc.) or via regex (like we do now). That sort of thing might make more sense.

**Comment by andrewjtimmons** [comment]
That makes sense.  Thanks for taking the time to think about it and reply and maintain this cool too! 

Cheers!
